# Generated by Django 4.2.1 on 2023-07-07 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='Categories')),
                ('parent', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.CASCADE, to='ProductApi.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OurAdds',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='our Adds')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('rating', models.IntegerField()),
                ('brand', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(blank=True, upload_to='Thumbnail')),
                ('images', models.ImageField(
                    blank=True, null=True, upload_to='Images')),
                ('discount', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('IdCard', models.ImageField(null=True, upload_to='Id')),
                ('image', models.ImageField(null=True, upload_to='Id')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='category_name', to='ProductApi.categories')),
                ('colors', models.ManyToManyField(
                    related_name='color', to='ProductApi.color')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=255, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('profile', models.ImageField(blank=True, upload_to='ShopProfile')),
                ('cover', models.ImageField(
                    blank=True, null=True, upload_to='ShopCover')),
                ('telephone', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('password', models.CharField(default='Ngoga', max_length=255)),
                ('idCard', models.ImageField(upload_to='Id')),
                ('image', models.ImageField(upload_to='Owners')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Test')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(
                    max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(
                    blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=255)),
                ('profile', models.ImageField(upload_to='Profile')),
                ('coverPhoto', models.ImageField(upload_to='Profile')),
                ('library', models.ImageField(
                    blank=True, null=True, upload_to='Profile')),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.IntegerField(default=0)),
                ('shopid', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='ProductApi.shop')),
                ('userid', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.BooleanField()),
                ('shopid', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='ProductApi.shop')),
                ('userid', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShopFollowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.IntegerField()),
                ('shopid', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='ProductApi.shop')),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('ratecount', models.TextField()),
                ('shopid', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='ProductApi.shop')),
                ('userid', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='Profile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='profileimages', to='ProductApi.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('Productimage', models.ImageField(
                    blank=True, upload_to='Images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='proimages', to='ProductApi.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='seller_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='shop_name', to='ProductApi.shop'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Updates', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('app notification', 'app notification'), (
                    'other notification', 'other notification')], default='app notification', max_length=255)),
                ('message', models.TextField()),
                ('recipient', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField()),
                ('dislike', models.IntegerField()),
                ('shopid', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='ProductApi.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('shopid', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='ProductApi.shop')),
                ('userid', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
