# Generated by Django 4.2.1 on 2023-05-09 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApi', '0002_alter_product_category_alter_product_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='Images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='Thumbnail'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productimages', models.ImageField(blank=True, upload_to='Images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proimages', to='ProductApi.product')),
            ],
        ),
    ]
