# Generated by Django 4.2.1 on 2023-06-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApi', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='idCard',
            field=models.ImageField(default='okay', upload_to='Id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(default='okay', upload_to='Owners'),
            preserve_default=False,
        ),
    ]
