# Generated by Django 4.2.1 on 2023-05-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApi', '0003_alter_product_images_alter_product_thumbnail_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='ProductImages',
        ),
        migrations.RenameField(
            model_name='productimages',
            old_name='Productimages',
            new_name='Productimage',
        ),
    ]
