# Generated by Django 4.2.1 on 2023-07-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApi', '0006_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('created', models.DateTimeField()),
                ('username', models.CharField(max_length=255)),
            ],
        ),
    ]
