# Generated by Django 4.2.1 on 2023-05-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApi', '0007_rename_testimage_testimagereact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Test')),
            ],
        ),
        migrations.DeleteModel(
            name='TestImageReact',
        ),
    ]
