# Generated by Django 4.2.1 on 2023-07-13 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApi', '0007_verificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
