# Generated by Django 4.2.1 on 2023-07-14 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApi', '0008_alter_verificationcode_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
