# Generated by Django 4.2.1 on 2023-08-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApi', '0009_shopverificationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transId', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('statusCode', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('trackId', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
