# Generated by Django 4.2.1 on 2023-05-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApi', '0011_remove_product_colors_product_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(related_name='color', to='ProductApi.color'),
        ),
    ]
