# Generated by Django 4.2.1 on 2023-08-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApi', '0012_freecredit'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255, null=True)),
                ('url', models.URLField()),
            ],
        ),
    ]
