# Generated by Django 4.2.1 on 2023-08-26 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApi', '0013_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='place',
            field=models.CharField(default='Normal', max_length=255),
        ),
    ]
