# Generated by Django 4.2.1 on 2023-05-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApi', '0014_userprofile_profileimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='password',
            field=models.CharField(default='Ngoga', max_length=255),
        ),
    ]
