# Generated by Django 4.2.1 on 2023-05-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApi', '0015_shop_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='profile',
            field=models.ImageField(blank=True, upload_to='ShopProfile'),
        ),
    ]
