# Generated by Django 4.2.1 on 2023-08-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApi', '0015_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='thumbnail',
            field=models.ImageField(default='no Image', upload_to='News'),
        ),
    ]
