# Generated by Django 4.2.1 on 2023-08-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApi', '0016_news_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='device_token',
            field=models.TextField(default=''),
        ),
    ]
