# Generated by Django 4.2.1 on 2023-05-31 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApi', '0017_rating_like_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProductApi.categories'),
        ),
        migrations.AddField(
            model_name='shop',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='ShopCover'),
        ),
        migrations.AddField(
            model_name='shop',
            name='email',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.IntegerField()),
                ('shopid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductApi.shop')),
            ],
        ),
    ]
