# Generated by Django 4.2.1 on 2023-08-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApi', '0018_devicetokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
