# Generated by Django 4.2.1 on 2023-05-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApi', '0018_categories_parent_shop_cover_shop_email_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='liked',
            field=models.IntegerField(default=0),
        ),
    ]
