# Generated by Django 4.2.1 on 2023-09-01 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApi', '0019_jobs_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
