# Generated by Django 4.2.1 on 2023-09-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductApi', '0020_jobs_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
