# Generated by Django 4.2.1 on 2023-06-03 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProductApi', '0020_remove_like_liked_remove_like_userid_userlike'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Followers',
            new_name='shopFollowers',
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.BooleanField()),
                ('shopid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProductApi.shop')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
